#@title  load models and basic routines
import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding

try:
  import einops
except:
  #!pip install git+https://github.com/kernelmachine/transformers@openlm#egg=transformers
  !pip install -q bitsandbytes datasets  pyspellchecker peft datasets accelerate
  !pip install -q pyspellchecker einops

#from transformers import OpenLMForCausalLM, AutoTokenizer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForCausalLM
import os
device = 'cuda:0'
if not os.path.exists("/content/drive"):
  from google.colab import drive
  drive.mount('/content/drive')

import torch

try:
  if starcoder2_model is None: assert False
except:
  model_name = "pszemraj/long-t5-tglobal-base-16384-book-summary"
  #model_name = "BEE-spoke-data/pegasus-x-synthsumm_open_fv-P4-32k-neft_0.2"
  summary_tokenizer = AutoTokenizer.from_pretrained(model_name)
  summary_model = AutoModelForSeq2SeqLM.from_pretrained(model_name).cuda().eval()


  #silo_model = OpenLMForCausalLM.from_pretrained("kernelmachine/silo-pdswby-1.3b").half().cuda().eval()
  #silo_tokenizer = AutoTokenizer.from_pretrained("kernelmachine/silo-pdswby-1.3b")

  model_name = "bigcode/starcoder2-3b"
  #model_name = "TechxGenus/starcoder2-3b-instruct"
  starcoder2_tokenizer = AutoTokenizer.from_pretrained(model_name, padding_side="left")
  starcoder2_model = AutoModelForCausalLM.from_pretrained(model_name,
  #                                          attn_implementation="flash_attention_2",device_map="cuda:0",
                                            torch_dtype=torch.float16,
                                            ).cuda().eval()
  starcoder2_tokenizer.pad_token = starcoder2_tokenizer.eos_token

EU_langs = ['bg',
 'hr',
 'cs',
 'da',
 'nl',
 'en',
 'et',
 'fi',
 'fr',
 'de',
 'el',
 'hu',
 'ga',
 'it',
 'lv',
 'lt',
 'mt',
 'pl',
 'pt',
 'ro',
 'sk',
 'sl',
 'es',
 'sv']

def get_tokens_as_list(word_list, tokenizer):
    "Converts a sequence of words into a list of tokens"
    tokens_list = []
    for word in word_list:
        tokenized_word = tokenizer([word], add_special_tokens=False).input_ids[0]
        tokens_list.append(tokenized_word)
    return tokens_list

#Good luck!", "Good Luck", "Good luck",
#"<s>",
question_types = ["give", "state", "distinguish", "what", "where", "why", "how", "which", "can", "explain", "define", "list", "give", "discuss", "compare", "identify", "name", "write", "provide", "do", "can", "if", "in"]
summary_bad_words = get_tokens_as_list(word_list=["fuck", "pussy", "cunt", "nigger", "whore", "twat",],\
                                       tokenizer=summary_tokenizer)

starcoder2_bad_words = get_tokens_as_list(word_list=["fuck", "pussy", "cunt", "nigger", "whore", "twat",
                                              "https", "Wikinews", "wikinews",  "<KEY>", "<NAME>", "<EMAIL>", "<PASSWORD>", "<jupyter_output>","<empty_output>","<jupyter_text>", "<jupyter_code>", "<pr_status>", "<pr_is_merged>", "<pr_event_id>", "<pr_in_reply_to_review_id>", "<pr_review_state>", "<file_sep>",
                                              "<pr_diff_hunk_comment_line>", "<pr_in_reply_to_comment_id>", "<pr_file>", "<fim_middle>", "<file_sep>",
                                              "<fim_pad>", "<fim_prefix>","<fim_suffix>", "<|endoftempate|>", "<|endofgeneration|>.", "<|endof generation|>", "<|endofgeneration|question|>", "<pr>", "<|endofgeneration|question|>(", "<|>", "< |endofgeneration||>",
                                              "This text has been generated by", "OpenAI's", "GPT-3",
                                              "Please let me know if I can assist you with anything",
                                              "<|endoftext|>", "<|endoftext|><|endoftext|>",
                                              "Please let me know if there is anything else", "OpenAI", "openAI", "[END OF RESPONSE]", "<|endofgeneration|>", "GPT-3", "GPT-4", "OpenAI", "<|question_end|>",  "openai",
                                              "Due to the character limitations", "Word count", "Wordcount", "Word Count:", "Word Count", "word count"],\
                                        tokenizer=starcoder2_tokenizer)

import torch
def generate(model, tokenizer, user_prompt, max_new_tokens=20, no_repeat_ngram_size=4, position_ids=None, **args):
  with torch.no_grad():
    torch.cuda.empty_cache()
    inputs = tokenizer(user_prompt, return_tensors="pt", padding=True, truncation=True).to(device)
    outputs = model.generate(**inputs,  use_cache=True, bad_words_ids=starcoder2_bad_words if tokenizer== starcoder2_tokenizer else None, no_repeat_ngram_size=no_repeat_ngram_size, repetition_penalty=1.2, max_new_tokens=max_new_tokens, **args)
    torch.cuda.empty_cache()
    output =  tokenizer.batch_decode(outputs)
    return output



stop_words = {'need', 'about',  'because', 'through', "isn't", 'look', "shouldn't", "i've", 'yourself', 'wouldn', 'else', 'against', "mustn't", 'may', 'named', 'three', 'bring', 'bit', 'my', 'below', 'ma', 'everything', 'o',  'could', 'ready', 'followed', 'mr', 'at', 'to', 'was', 'happy', 'open', 'would', 'say', 'describing', 'weren', 'still', 'more', 'we', 'ever', 'doing',  'please',  'this', 'won', 'all', 'does', 'nor', 'can', 'right', 'hasn', 'illustrating', 'consisting', 'move', 'went', 'someone', 'isn', 'saying', 'find', 'ago', 'thank', 'yea', 'whom', 'they', 'want', 'lost', 'developed', 'of', 'aren', 'whatever', 'some', 'it', 'bad', "you'll", 'why', 'keep', "I'm", 'mine',  'too', 'big', 'true', 'searching', "that'll", 'wasn', 'as', 'including', 'idea', "you'd", 'ain', 'y', 'every', 'heard', 'him', '"', 'm', 'sir', 'one', 'them', 'long', 'by', 'turn', 'next', 'theirs', "wasn't", 'regarding', "he's", "hadn't", 'come', 'had', 'having', "i'm", "can't", 'yet', 'll', 'same', 'reserved', 'also', 'above', 'give', 'got', 'once', 'yourselves', 'sure', 'hers', 'and', 'few', 'those', 'shan', 'feel', 'is', 'let', 'do', 'mrs', 'yes', "mightn't", 'will', 'which', 'own', 'meet', 'just', 'am', 'guys', 'each', 'since', 'between', 'know', 'start', 'something', 'might', "couldn't", "let's", 'hey', 'any', 'illustrated', 'two', 'again', 'up', '.', 'continued', 'me', 'writing', 'ourselves', 'guess', 'search', 'but', 'there', 'not', 'didn', 'maybe', 'online',  'make', 'did', 'stay', 'have', 'be', 're', "didn't", 'nice', 'says', 'shared', 'rights', 'gone', 'last', 'die', 'if', 'haven', 'hope', 'comprising', 'seen', 'when', 'consisted', "you've", 'over', 'naming', 'first', "don't", "needn't", 'nothing', 'off', 'here', 'these', 'from', 'she', 'use', 'gonna', 'an', 'said', 'our', 'even', 'being', 'place', 'very', 'doesn', 'needn', 'their', 'going', 'her', 'on', 'herself', 'than', 'away', 'into', 'phone', 'yeah', '!', 'under', "I've", 'okay', 'tell',  'play', 'such', "doesn't", 'days', 'further', 'called', 'getting', 'however', "i'll", 'see', '?', 'whole', 'job', 'yours', 'developing', 'his', 'head', 'hard', 'way', 'hello', 'what', 'good', 'where', "you're", 'or', 'ours', "won't", 'been', 'get', 'myself', 'with', "it's", 'until', 'in', 'wanna', 'were', "hasn't", 'should', 'like', 'thanks', 'couldn', "that's", 'gotta', 'knew', 'he', 'how', 't', 'fine', 'mean', 'no', 'described', 'life', 'mustn', 'who', "aren't", 'mightn', 'sorry', 'thing', 'while', 'put', 'during', 'other', 'woman', 'comprised', 'its', 'following', 've', 'found', 'much', 'wait', 'you', "haven't", 'never', 'mom', 'hold',  'most', 'contact', 'i', 'took', "shan't",  'after', 'left', 'user', 'must', 'so', 'the', 'new', 'lot', 'room', 'used', 'that', 'd', 'care', 'boy', 'out', 'guy', 'back', 'huh',  'hear', 'continuing', 'ask', 'done', 'for', 'indeed', 'wants', 'well', "wouldn't", 'told', 's', 'are', 'old', "'", 'nonetheless', 'both', 'night', 'your', 'down', 'themselves', 'miss', 'think', 'before', 'a', 'run', 'alone', 'included', 'don', "there's", 'men', 'now', 'came', 'only', 'himself', 'try', 'then', 'itself', 'according', 'shouldn', 'looks', 'work', 'wrong', 'happened', 'has', "i'd", 'made', "she's", "should've", 'kind', 'saw', 'baby', ':', "weren't", 'hadn'}
common_words = {'name', 'girl', 'rest', 'flood', 'son', 'green', 'music', 'floor', 'kill',  'white', 'four', 'things', 'anybody', 'six', 'short', 'Trevor', 'money', 'ten', 'forty', 'Christmas', 'eat', 'present', 'wind', 'month', 'bird', 'dad','robins', 'cause', 'coffee', 'eight', 'comes', 'blue', 'kidding', 'behind', 'real', 'rain', 'enough', 'farm', 'full', 'juice', 'believe', 'box', "keep', 'done", 'live', 'half', 'world', 'great', 'broke', 'friend', 'eggs', 'horse', 'later', 'mouth', 'cut', 'reading', 'cute', 'different', 'pink', 'sit', 'stand', 'small', 'yellow', 'nest', 'years', 'Monday', 'girls', 'spring', 'today', 'brown', 'road',  'rob', 'dry', 'eleven', 'triangle', 'heart', 'remember', 'wife', 'god','fun', 'supposed', 'English', 'help', 'glass', 'chapter', 'people', 'God', 'bear', 'afraid', 'take',  'key', 'draw', 'teach', 'eye', 'child', 'train', 'fat', 'thought', 'already', 'bucks', 'cold', 'hair', 'lunch', 'afternoon', 'home', 'stop', 'married', 'yesterday', 'tall', 'second', 'forget', 'fruit', 'side', 'rice',  'started', 'either', 'boat', 'wanted', 'twenty', 'making', 'line', 'paper', 'een', 'sore', 'tree', 'weekend', 'party', 'sister', 'birds', 'thirty', 'year', 'part', 'graduate', 'tape', 'watched', 'pull', 'read', 'favorite', 'time', 'bye', 'Sunday', 'outside', "teacher's", 'wash', 'asked', 'Wednesday', 'water', 'muddy', 'goes', 'walk', 'alright', 'around', 'five', 'damn', 'book', 'eighty', 'bus', 'mother', 'cot', 'broken', 'wolf', 'crow', 'really', 'hand', 'end', 'leave', 'dead', 'cabin', 'red', 'silly', 'far', 'deal', 'light', 'Tuesday', 'place', 'class', 'hospital', 'fell', 'check', 'buy', 'egg', 'wear', 'game', 'dog', 'crazy', 'tough','house', 'day',  'Friday', 'mad', 'father', 'anything', 'Saturday', 'television', 'spelling', 'Travis', 'fall', "what's", 'fix', 'lay', 'friends', "I'll", 'write', 'always', 'minutes', 'dirty', 'card', 'ice', 'Stephanie', 'flowers', 'bag', 'mine', 'children', 'morning', 'opener',  'hundred', 'change', 'safely', 'social', 'animal', 'playing', 'hot', 'pick', 'summer', 'foot', 'watch', 'food', 'tomorrow', 'yep', 'mhmm', 'nose', 'radio', 'gosh',  'study', 'sides', 'week', 'best', 'bed', 'brother', 'chair', 'wheel', 'listen', 'better', 'beautiful', 'close', 'quiet', 'soon', 'friendly', 'color', 'pretty', 'street', 'inside', 'hit', 'finish', 'break', 'black', 'hours', 'probably', 'love', 'funny', 'store',   'drive', 'dinner', 'birthday', 'picture', 'building', 'cry', 'fast', 'tonight', 'call', 'high', 'animals',  'hurt', 'stuff', 'seven', 'clean', 'nurse', 'hat', 'school', 'soft', 'snow', 'hell', 'table', 'free', 'nine', 'many', 'working', 'neat', 'carry', 'door','little', 'studies', 'sat','man',  'watching', 'quit', 'sun','mind', 'glasses', 'pass', 'fire', 'feet', 'push', 'face','car', 'feed', 'show', 'talk', }

assistant_personality = ['heartwarming', 'trustworthy', 'empathetic', 'calm', 'friendly', 'honest', 'stoic', 'sincere', 'satirical', 'gothic', 'humorous', 'outgoing', 'conscientious', 'ambitious', 'amiable', 'hopeful', 'positive', 'diligent', 'attractive', 'optimistic', 'sympathetic', 'brassy', 'patient', 'playful', 'respectful', 'peculiar', 'radiant', 'melancholic', 'gloomy', 'rejuvenated', 'pensive', 'supportive', 'bold', 'invigorated', 'imaginative', 'sultry', 'strong', 'grave', 'steadfast', 'open-minded', 'philosophical', 'reliable', 'tranquil', 'humble', 'quick-witted', 'bizarre', 'powerful', 'concise', 'vibrant', 'charming', 'spirited', 'enthusiastic', 'wise', 'liberated', 'encouraging', 'exuberant', 'whimsical', 'ironical', 'dynamic', 'spontaneous', 'bubbly', 'macabre', 'intelligent', 'zealous', 'courageous', 'grateful', 'warm', 'uplifted', 'terse', 'seductive', 'mocking', 'tenacious', 'motivated', 'creative', 'innovative', 'offbeat', 'resilient', 'unpredictable', 'composed', 'enigmatic', 'fanciful', 'inspiring', 'sarcastic', 'gentle', 'reserved', 'sneering', 'flexible', 'respected', 'loving', 'generous', 'faithful', 'cheeky', 'austere', 'nurturing', 'sombre', 'cynical', 'succinct', 'animated', 'devoted', 'approachable', 'lively', 'invigorating', 'ridiculing', 'cutting', 'fearless', 'compassionate', 'adventurous', 'scornful', 'determined', 'astute', 'quiet', 'silent', 'curious', 'gracious', 'witty', 'magnetic', 'feisty', 'odd', 'impactful', 'audacious', 'tight-lipped', 'discerning', 'luminous', 'cooperative', 'cryptic', 'jubilant', 'selfless', 'vigorous', 'joyful', 'harmonious', 'eloquent', 'graceful', 'resolute', 'noble', 'charismatic', 'affable', 'outlandish', 'genuine', 'charitable', 'brief', 'assertive', 'mysterious', 'vivacious', 'tolerant', 'dependable', 'unconventional', 'heroic', 'serene', 'daring', 'bright', 'versatile', 'energetic', 'carefree', 'brooding', 'mindful', 'confident', 'sardonic', 'persistent', 'benevolent', 'pleasant', 'balanced', 'eccentric', 'passionate', 'irreverent', 'adaptable', 'flirtatious', 'forceful', 'cheerful']

age_groups = [
    "Infant/Toddler (0-2 years)",
    "Preschooler (3-5 years)",
    "Young Child (6-8 years)",
    "Older Child(9-11 years)",
    "Adolescent (12-18 years)",
    "Young Adult (19-25 years)",
    "Adult (26-55 years)",
    "Mature Adult (56-65 years)",
    "Senior/Retired Person (66 years and over)"
]
sexual_orientation = ["Male", "Female", "LGBTQ"]

location = ["North America", "South America", "Asia", "Africa", "Europe", "Oceania"]

style = ["Lyrical", "Spoken", "Interview", "Interactive Discussion", "Narrative", "News Report", "Sports Report", "Narrative Blog", "How-to", "Recipe", "Informational Description",
         "Encyclopedia Article", "Research Article", "Descriptive Article", "FAQ", "Opinion", "Review", "Opinion Blog",
         "Denominational Religious Blog or Sermon", "Informational Persuasion", "Sales Pitch", "News and Opinon Blog or Editoral", ]

length = ["Long", "Short", "Medium", "One Paragraph", "Two Paragraph", "Five Paragraph", "1000 words", "10 words", "100 words"]

race_national_origin = ["White", "Black", "Asian", "European", "Turkish",
    "Spanish",
    "Greek",
    "Italian",
    "French",
    "American",
    "Mexican",
    "Canadian",
    "Brazilian",
    "Peruvian",
    "Argentinean",
    "Colombian",
    "Venezuelan",
    "Ethiopian",
    "Moroccan",
    "South African",
    "Nigerian",
    "Egyptian",
    "Chinese",
    "Japanese",
    "Indian",
    "Thai",
    "Korean",
    "Australian",
    "New Zealand",
    "Polynesian",
    "Hawaiian",
    "Singaporean"]

professions = [
    "Engineer",
    "Doctor",
    "Nurse",
    "Teacher",
    "Software Developer",
    "Data Scientist",
    "Lawyer",
    "Pharmacist",
    "Researcher",
    "Accountant",
    "Architect",
    "Chef",
    "Dentist",
    "Journalist",
    "Pilot",
    "Photographer",
    "Police Officer",
    "Veterinarian",
    "Writer",
    "Painter",
    "Musician",
    "Athlete",
    "Actor",
    "Psychologist",
    "Carpenter",
    "Electrician",
    "Plumber",
    "Social Worker",
    "Farmer",
    "Mechanic"
]

life_skills = [
    "Critical Thinking",
    "Problem Solving",
    "Communication",
    "Teamwork",
    "Adaptability",
    "Time Management",
    "Organization",
    "Creativity",
    "Emotional Intelligence",
    "Leadership",
    "Self-Motivation",
    "Stress Management",
    "Decision Making",
    "Assertiveness",
    "Resilience",
    "Empathy",
    "Negotiation",
    "Conflict Resolution",
    "Budgeting",
    "Computer Literacy",
    "Foreign Language",
    "Cultural Awareness",
    "Networking",
    "Personal Hygiene",
    "Cooking",
    "First Aid"
]

media_2_sections = {'play': ['scene', 'character', 'dialog'], 'novel': ['chapter', 'character', 'narration'], 'essay': ['introduction', 'body', 'conclusion'], 'paper': ['abstract', 'introduction', 'methodology', 'results', 'discussion', 'conclusion'], 'news article': ['headline', 'byline', 'body', 'source'], 'poem': ['stanza', 'line', 'verse', 'rhyme scheme'], 'film script': ['scene', 'character', 'dialog', 'action'], 'short story': ['beginning', 'middle', 'end', 'character', 'narration'], 'scientific journal article': ['abstract', 'introduction', 'related work', 'methodology', 'results', 'discussion', 'conclusion', 'references'], 'interview transcript': ['question', 'answer', 'participant'], 'movie': ['scene', 'character', 'dialog'], 'podcast': ['episode', 'host', 'guest', 'discussion'], 'article': ['title', 'author', 'body', 'source'], 'comic': ['strip', 'character', 'dialog', 'narration'], 'magazine': ['cover', 'table of contents', 'article', 'advertisements'], 'documentary': ['introduction', 'interview', 'footage', 'voiceover', 'conclusion'], 'rant': ['topic', 'opinions', 'arguments'], 'online conversation': ['participants', 'messages', 'timestamps'], 'intimate conversation between close people': ['emotion', 'exchange', 'affection'], 'bedtime lullaby': ['lyrics', 'melody', 'repetition'], 'lecture': ['topic', 'speaker', 'slides', 'Q&A']}
media_types = list(media_2_sections.keys())

genres = [
    "art",
    "science",
    "science fiction",
    "research paper",
    "high school essay",
    "scientific journal",
    "code documentation",
    "social media post",
    "food blog",
    "historical fiction",
    "romance",
    "fantasy",
    "mystery",
    "horror",
    "adventure",
    "drama",
    "comedy",
    "thriller",
    "action",
    "western",
    "documentary",
    "biography",
    "autobiography",
    "self-help",
    "philosophy",
    "religion",
    "psychology",
    "sociology",
    "history",
    "economics",
    "politics",
    "business",
    "finance",
    "technology",
    "computer science",
    "programming",
    "software development",
    "data science",
    "machine learning",
    "artificial intelligence",
    "cybersecurity",
    "cryptocurrency",
    "blockchain",
    "gaming",
    "music",
    "film",
    "literature",
    "poetry",
    "theater",
    "dance",
    "culinary",
    "photography",
    "fashion",
    "travel",
    "fitness",
    "sports",
    "health",
    "wellness",
    "parenting",
    "education",
    "language learning",
    "cooking",
    "baking",
    "home improvement",
    "gardening",
    "crafts",
    "DIY",
    "puzzle",
    "board game",
    "card game",
    "video game",
    "virtual reality",
    "augmented reality",
    "comic book",
    "graphic novel",
    "anime",
    "manga",
    "science magazine",
    "fashion magazine",
    "lifestyle magazine",
    "travel blog",
    "technology blog",
    "personal development blog",
    "fitness blog",
    "parenting blog",
    "book review blog",
    "podcast",
    "vlog",
    "webcomic",
    "satire",
    "political commentary",
    "travelogue",
    "recipe book",
    "graphic design",
    "interior design",
    "architectural design",
    "product design",
    "user interface design",
    "web design",
    "game design",
    "environmental science",
    "zoology",
    "botany",
    "geology",
    "astronomy",
    "chemistry",
    "physics",
    "mathematics",
    "literary fiction",
    "contemporary fiction",
    "short story",
    "poetry anthology",
    "cookbook",
    "business plan",
    "graphic design portfolio",
    "art exhibition catalog",
    "erotic",
    "porn",
    "spam",
    "advertisement"
]

mmlu_list = ['human ecology', 'human anatomy', 'asian history', 'african history', 'south american history', 'middle eastern history', 'comparative religion', 'comparative law', 'organizational behavior', 'atomic data', 'cognitive-behavioral therapy', 'data structures', 'political ideologies', 'world religions', 'number theory', 'biomedical engineering', 'elementary particles', 'branding strategies', 'aesthetics', 'international trade law', 'topology', 'classical antiquity', 'socioeconomic aspects of aging', 'social change', 'fluid dynamics', 'justice theory', 'genomics', 'environmental issues', 'gravitation', 'electricity and magnetism', 'data collection', 'moral disputes', 'reinforcement learning', 'programming basics', 'confidence intervals', 'inorganic chemistry', 'forensic computing', 'circuit analysis', 'geometry', 'conceptual physics', 'cold war', 'mechanical waves','project management', 'viral genetics', 'plasmas', 'business ethics', 'evolution', 'human body', 'real analysis', 'arithmetic', 'environmental chemistry', 'clinical psychology', 'immunology', 'consumer behavior', 'longevity', 'forecasting', 'data encryption', 'relativity', 'energy conservation', 'philosophical debates', 'managerial accounting', 'reproductive system', 'renaissance art', 'world systems theory', 'media relations', 'critical legal studies', 'correlation', 'statistics', 'surgery', 'algorithm', 'networks', 'ageism', 'algebra of random variables', 'internet basics', 'high school european history', 'monetary policy', 'human reproductive systems', 'decision-making processes', 'economic cycles', 'bronze age', 'nervous system', 'jurisprudence', 'organic chemistry', 'epidemiology', 'brand management', 'case law',  'marketing', 'post hoc ergo propter hoc', 'neutrinos', 'national policy', 'college medicine', 'metaphysics', 'epistemology', 'human geography', 'vaccine development', 'emergency medicine', 'jurisprudence theories', 'orthopedics', 'computer network', 'respiratory anatomy', 'family planning', 'electrical engineering', 'geopolitical analysis', 'industrialization', 'robotics', 'psychiatry', 'atomic processes', 'human rights', 'stoichiometry', 'nutritional epidemiology', 'population genetics', 'biogerontology', 'fluid mechanics', 'blood brain', 'abstract algebra', 'miscellaneous', 'high school psychology', 'newtonian', 'endocrine system', 'cell biology', 'astrochemistry', 'judicial systems', 'learning theories', 'medical imaging', 'survival analysis', 'world war i', 'cardiovascular anatomy', 'college biology', 'religious philosophy', 'moral scenarios', 'nuclear physics', 'dermatology', 'cognitive dissonance', 'mitosis', 'computer graphics', 'symbolic logic', 'international alliances', 'developmental stages', 'cardiovascular system', 'problem-solving skills', 'formal logic', 'utilitarianism', 'trade agreements', 'galois theory', 'regression analysis', 'experimental design',  'management', 'materials chemistry', 'religious conflicts', 'set theory', 'diplomatic strategies', 'environmental statistics', 'prehistoric europe', 'globalization', 'diet-related diseases', 'sales and marketing', 'cultural diversity', 'internet security', 'hypothesis testing', 'straw man', 'fascism', 'ethical conflicts', 'healthcare for elderly', 'high school physics', 'market segmentation', 'professional accounting', 'acceleration of',  'economic indicators', 'unsupervised learning', 'human genome project', 'childhood nutrition', 'sexual health education', 'stakeholder engagement', 'internal medicine', 'conflict resolution', 'ethics', 'time series analysis', 'economic theories', 'software development', 'DNA replication', 'world conflicts', 'fiscal policy', 'production theory', 'renaissance', 'cryptography', 'black hole', 'clinical trials', 'colonialism', 'infant mortality', 'european union', 'whistleblowing', 'compliance and risk management', 'neural networks', 'world economies', 'general practice', 'corporate communications', 'theology', 'developmental biology', 'foreign aid', 'algorithms', 'senior health', 'professional psychology', 'sexual development',  'enlightenment', 'trigonometry', 'sociology',  'circulatory system', 'market structures', 'geology', 'public relations', 'ecology', 'acids and bases', 'population studies', 'socialism', 'stone age', 'spectroscopy', 'market analysis', 'totalitarianism', 'human-computer interaction', 'statistical mechanics', 'bayesian inference', 'antiviral treatments', 'peace negotiations', 'labor economics', 'artificial intelligence', 'business law', 'major world religions', 'physical geography', 'newtonian mechanics', 'food safety', 'political parties', 'unemployment', 'climate zones', 'confirmation bias', 'national security', 'data interpretation', 'criminal law', 'mathematical reasoning', 'electrodynamics', 'historical demographics', 'diagnostic methods', 'power systems', 'periodic table', 'basic geometry', 'enzymology', 'modern era', 'cognitive psychology', 'democratic process', 'tax accounting', 'trade economics', 'atomic physics', 'labor ethics', 'exploration', 'prehistoric culture', 'high school computer science', 'behavioral therapy', 'obstetrics and gynecology', 'econometrics', 'social psychology', 'sexual ethics', 'operating systems', 'nutrition', 'cosmology', 'augmented reality', 'threat models', 'forensic accounting', 'civil war', 'supramolecular chemistry', 'semiconductors', 'molecular processes',  'map reading', 'deontology', 'philosophy',  'college chemistry', 'war crimes', 'social structures', 'ancient civilizations', 'statistical methods',  'databases', 'reproductive anatomy', 'industrial revolution', 'us foreign policy', 'public policies', 'social theory', 'algebra i', 'space race', 'astroparticle physics', 'skeletal system', 'analytical chemistry', 'quantum mechanics', 'high school government and politics', 'medieval period', 'data mining', 'panel data', 'algebra', 'international advocacy', 'patient care', 'prehistory', 'risk management', 'genetic disorders', 'epigenetics', 'human sexuality', 'sustainability', 'auditing', 'internet age', 'property law', 'conflict resolution strategies', 'descriptive statistics', 'treatment planning', 'multivariate analysis', 'photosynthesis', 'computational thinking', 'experimental psychology', 'natural law', 'high school chemistry', 'ethical hacking', 'galaxies',  'logical fallacies','clinical knowledge', 'correlation coefficient', 'virtue ethics', 'logic', 'contemporary history', 'control systems', 'cultural norms', 'high school biology', 'prehistoric art', 'chemical reactions', 'optics', 'econometric models', 'quick sort', 'syllogistic logic', 'module theory', 'photonics', 'virology', 'management science', 'intelligence analysis', 'urinary system', 'biochemistry', 'public health nutrition', 'elasticity', 'lymphatic system', 'conflict theory', 'radiology', 'specialized medicine', 'radiochemistry', 'software engineering', 'american revolution', 'electromagnetism', 'game theory', 'theorem', 'college physics', 'inflation', 'physical chemistry', 'hydrodynamics', 'respiratory system', 'numerical analysis', 'meiosis', 'deductive reasoning',   'microelectronics', 'resource allocation', 'election processes', 'anatomy', 'dark matter', 'health systems', 'reproductive rights', 'constitutional principles', 'virtual reality', 'sexual health', 'global facts', 'civic duties', 'population statistics', 'legal studies', 'exoplanets', 'legal positivism', 'epidemiology of viruses', 'iron age', 'abnormal psychology', 'optics', 'international sanctions', 'middle ages', 'complex analysis', 'machine learning', 'STDs prevention', 'high school mathematics', 'nuclear chemistry', 'topography', 'high school geography', 'data analysis techniques', 'gene therapy', 'progressive era', 'oncology', 'world capitals', 'strategic management', 'space exploration', 'aging process', 'high school microeconomics', 'imperialism', 'geopolitical facts',  'international law', 'digestive anatomy', 'moral judgments', 'differential equations', 'contract law', 'neuropsychology', 'chemical bonds', 'jurisprudence ethics', 'cloud computing', 'mechanics', 'equation of state', 'decimals', 'proteomics', 'quantum chemistry', 'gender identity', 'pediatrics', 'magnetohydrodynamics', 'physiology', 'stakeholder theory', 'age-related diseases', 'oceanography', 'pre-calculus', 'nebulae', 'practical ethics', 'legal theory', 'tort law', 'anesthesiology', 'professional medicine', 'mathematical proof', 'cybersecurity', 'digital marketing', 'feudalism', 'high school macroeconomics', 'constitutional law', 'comparative law', 'molecular biology', 'defense strategies', 'astronomy', 'preventive medicine', 'nuclear reactions', 'high school us history', 'particle physics', 'maritime laws', 'personality theories', 'homomorphisms', 'planets', 'ad hominem', 'international courts', 'polynomials', 'modal logic', 'welfare economics', 'medicinal chemistry', 'operations management', 'integumentary system', 'crisis management', 'fallacies', 'viral diseases', 'treaties', 'world war ii', 'chemical kinetics', 'nanotechnology', 'relativistic', 'psychoanalysis', 'fair trade', 'professional law', 'causal inference', 'government branches', 'cultural sociology', 'space age', 'probability', 'computer security', 'analysis of variance', 'pharmacology', 'elementary mathematics', 'calculus', 'world wars', 'security protocols', 'genetics', 'truth tables', 'supervised learning', 'psychological assessment', 'magnetic fields', 'humanistic psychology', 'economic policy', 'communism',  'cardiac', 'gerontology', 'taxonomy', 'philosophical logic', 'great depression', 'quantum concepts', 'cross-border laws', 'sample survey methods', 'consumer theory', 'meteorology', 'disease management', 'corporate responsibility', 'linear algebra', 'gastrointestinal', 'intestinal', 'corporate governance', 'digestive system', 'limbic system', 'democracy', 'moral reasoning', 'civil rights movement', 'religious practices', 'thermodynamics', 'microbiology', 'cardiology', 'psychological disorders', 'high school world history', 'biological classification', 'modern physics',  'financial accounting', 'dietary guidelines', 'muscular system', 'simple algebra', 'dark energy', 'medical genetics', 'statistical inference', 'normal distribution', 'security studies', 'sexual orientation', 'cognitive aging', 'human aging', 'algebraic structures', 'logical connectives', 'high school statistics',  'diplomacy', 'pathology', 'market failure', 'solid state physics', 'cartography', 'quantifiers', 'ethical dilemmas', 'network security', 'college mathematics', 'civil rights', 'malware analysis', 'nationalism', 'deep learning',  'combinatorics', 'black holes', 'group theory', 'college computer science']


import json



from transformers import (
    StoppingCriteria,
    StoppingCriteriaList,
    TextIteratorStreamer,
)


#temperature=0.7, top_p=0.7, top_k=50,
def qet_query(answer):
    answer_arr = answer.split(". ")
    for _ in range(3):
      if len(answer_arr) < 5:
          query2 = [q for q in instruction_gen_tokenizer.batch_decode(instruction_gen_model.generate(**instruction_gen_tokenizer(". ".join(answer_arr), max_length=512, truncation=True, return_tensors="pt").to(device), max_length=512,   min_length=1, ), skip_special_tokens=True) if 'TypingMind.com' not in q and 'ChatHub' not in q]
          if not query2: continue
          query2 = query2[0].strip()
      elif len(answer_arr) < 10:
          ans1 = ". ".join(answer_arr[:5])+"."
          ans2 = ". ".join(answer_arr[5:])+"."
          query2 = [q for q in instruction_gen_tokenizer.batch_decode(instruction_gen_model.generate(**instruction_gen_tokenizer([ans1, ans2], max_length=512, padding=True, truncation=True, return_tensors="pt").to(device), max_length=512, min_length=1,  ), skip_special_tokens=True) if 'TypingMind.com' not in q and 'ChatHub' not in q]
          query3 = []
          for q in query2:
            q2 = ""
            for s in q.split(". "):
              if any(s in q3 for q3 in query3):
                continue
              q2 += ". "+s
            q2 = q2.strip()
            q2 = q2.lstrip(".")
            if q2:
              query3.append(q2)
          if not query3: continue
          query2 = "\n".join([query3[0]]+[q.replace(" a ", " the ").replace(" an ", " the ") for q in query3[1:] if "following" not in q and " this " not in q and " summar" not in q and "grammar" not in q])
      else:
          ans1 = ". ".join(answer_arr[:5])+"."
          ans2 = ". ".join(answer_arr[5:10])+"."
          ans3 = ". ".join(answer_arr[-10:])+"."
          query2 = [q for q in instruction_gen_tokenizer.batch_decode(instruction_gen_model.generate(**instruction_gen_tokenizer([ans1, ans2, ans3], max_length=512, padding=True, truncation=True, return_tensors="pt").to(device), max_length=512,   min_length=1, ), skip_special_tokens=True) if 'TypingMind.com' not in q and 'ChatHub' not in q]
          query3 = []
          for q in query2:
            q2 = ""
            for s in q.split(". "):
              if any(s in q3 for q3 in query3):
                continue
              q2 += ". "+s
            q2 = q2.strip()
            q2 = q2.lstrip(".")
            if q2:
              query3.append(q2)
          if not query3: continue
          query2 = "\n".join([(query3[0]).strip()]+[q.replace(" a ", " the ").replace(" an ", " the ").strip() for q in query3[1:] if "following" not in q and " this " not in q and " summar" not in q and "grammar" not in q])
      if ("following" in query2 or " summar" in query2 or "grammar" in query2):
        continue

    return query2

import numpy as np
import os, tqdm
from collections import Counter
import random, math
import json
try:
  from datasets import load_dataset
except:
  !pip install -q datasets huggingface_hub matplotlib fast-pytorch-kmeans

from fast_pytorch_kmeans import KMeans

def is_contiguous(arr):
  """determine if the ints in the arr are continguous (1, 2, 3, 4) or not"""
  start = None
  prev = None
  contiguous=True
  for i in arr:
    if start is None:
      start = i
    if prev is None or i == prev+1:
      prev = i
      continue
    contiguous = False
    break
  return contiguous, start, i+1


def get_np_memmap_length(filename, shape, dtype=np.float32, ):
  """find the number of items in the mmap"""
  if not os.path.exists(filename):
    return shape[0]
  else:
    size = np.dtype(dtype).itemsize*np.prod(shape[1:])
    return int(os.path.getsize(filename)/size)

def np_memmap(filename, embeds=None, idxs=None, shape=None, dtype=np.float32, offset=0, order='C' ):
  """
  convienence funciton to create, set and return items from a mmap file. useful for dealing with embeddings that are larger than RAM.
  create a mmap if one doesn't exist. insert embeds into the mmap. if idxs are passed in, then set the embeds for just those idxs.
  if no embeds is passed in, then return just idxs items from the mmap file, or the whole mmap file otherwise."""

  if not filename.endswith(".mmap"):
    filename = filename+".mmap"
  if os.path.exists(filename):
    mode = "r+"
  else:
    mode = "w+"
  if shape is None and embeds is not None:
    shape = embeds.shape
  if not shape: shape = [0, 1]
  memmap = np.memmap(filename, mode=mode, dtype=dtype, shape=tuple(shape), offset=offset, order=order)
  cont = False
  if idxs:
    cont, start, end = is_contiguous(idxs)
  if embeds is None:
    if cont:
      return memmap[start:end]
    elif idxs:
      return memmap[idxs]
    else:
      return memmap

  if tuple(shape) == tuple(embeds.shape):
    memmap[:] = embeds
  elif cont:
    memmap[start:end] = embeds
  elif idxs:
    memmap[idxs] = embeds
  else:
    memmap[:] = embeds

  return memmap



def _cluster_one_batch(true_k,  spans, clusters, span2cluster_label, level, cluster_embeddings, min_overlap_merge_cluster, device):
    """
    internal function used to cluster one batch of embeddings. returns the new_labels and changes clusters and span2cluster_label
    """
    with torch.no_grad():
      embeddings = torch.from_numpy(cluster_embeddings)
      km = KMeans(n_clusters=true_k, mode='cosine')
      km_labels = km.fit_predict(embeddings.to(device=device, dtype=torch.float32)).tolist()
      embeddings = None
      # labels start from 1km_labels = [l.item() for l in km_labels.cpu()
    if not clusters:
      label2label = {}
      for span, label in zip(spans, km_labels):
        label = (label, level)
        if label not in label2label:
          label2label[label] = (span[0], level)
        label = label2label[label]
        clusters[label] = clusters.get(label, [])+[span]
        span2cluster_label[span] = label
      return list(clusters.keys())

    tmp_cluster = {}
    for span, label in zip(spans, km_labels):
      tmp_cluster[label] = tmp_cluster.get(label, [])+[span]
    new_labels = []
    #print (len(tmp_cluster), tmp_cluster)
    #create unique (level, id) labels and merge if necessary
    for a_cluster in tmp_cluster.values():
      for span in a_cluster:
        need_labels = [span for span in a_cluster if span not in span2cluster_label or span2cluster_label[span][1] != level]
        cluster_labels =[span2cluster_label[span] for span in a_cluster if span in span2cluster_label and span2cluster_label[span][1] == level]
        if not need_labels: continue
        if not cluster_labels:
          label = (span[0], level)
        else:
          most_common = Counter(cluster_labels).most_common(1)[0]
          if most_common[1] < min_overlap_merge_cluster:
            label = (span[0], level)
          else:
            label = most_common[0]
        new_labels.append(label)
        for span in need_labels:
          clusters[label] = clusters.get(label, [])+[span]
          span2cluster_label[span] = label
    return new_labels

def create_hiearchical_clusters(mmap_file, embed_dim, mmap_dtype=np.float32, force_recluster_idxs=None, mmap_len=None, max_level=4, max_cluster_size=200, min_overlap_merge_cluster=2, prefered_leaf_node_size=None, kmeans_batch_size=250000, \
                                use_tqdm=False, step_size_percentage=0.7, max_num_retries_cluster=3, recluster_threshold=0.5, device="cuda:0", clusters=None, span2cluster_label=None):
  """
  Incremental aglomerative hiearchical clustering from ALL embeddings stored in a mmap file. Will cluster new items added to the file.
  with 4 levels, and each node containing 200 items, we can have up to 1.6B items approximately
  span2cluster_label maps a child span to a cluster label. spans are of the form (index into mmap, hiearchical level).
  clusters maps a cluster label  => list of child spans.
  cluster labels are just the first span in the child span list.
  when we use the term 'idx', we normally refer to the index in an embedding file and we refer to spans as the tuples
  :arg mmap_file                      Name of file where the data is stored
  :arg embed_dim                      The dimension of the vector for the emebdding
  :arg mmap_dtype                     The dtype for the mmap file
  :arg mmap_len                       Number of items in mmap_file
  :arg force_recluster_idxs:          Optioal. if provided, the particular embedding idx that will be clustered in this call.
  :arg max_level:                     The maximum level of the cluster hiearchy.
  :arg max_cluster_size:              The maximum size of any particular cluster.
  :arg min_overlap_merge_cluster.     When incremental clustering, the minimum overlap between one cluster and another before merging them.
  :arg kmeans_batch_size:             The size of each batch of embeddings that are kmean batched.
  :arg use_tqdm:                      Whether to report the progress of the clustering.
  :arg device:                        The device on which to run the clustering
  """
  dtype = mmap_dtype
  if mmap_len is None:
    mmap_len = get_np_memmap_length(mmap_file, [0, embed_dim], dtype=dtype)
  if clusters is None:
    clusters = {}
  if span2cluster_label is None:
    span2cluster_label = {}
  if force_recluster_idxs:
    force_recluster_idxs = set(force_recluster_idxs)
  else:
    force_recluster_idxs = ()
  already_clustered = set([span[0] for span in span2cluster_label if span[1] == 0 and span[0] not in force_recluster_idxs])
  idxs = []
  if force_recluster_idxs:
    idxs = list(force_recluster_idxs)
    force_recluster_idxs = None
  idxs.extend([idx for idx in range(mmap_len) if idx not in already_clustered])
  if not idxs: return
  already_clustered = list(already_clustered)
  if len(already_clustered)  > int(.5*kmeans_batch_size):
    idxs.extend(random.sample(already_clustered, int(.5*kmeans_batch_size)))
  else:
    idxs.extend(already_clustered)
  already_clustered =  None
  idxs.extend([span[0] for span in span2cluster_label if span[1] != 0])
  idxs = list(set(idxs))
  random.shuffle(idxs)
  if not prefered_leaf_node_size:
    prefered_leaf_node_size= int (max_cluster_size*.7)
  for level in range(max_level):
    all_spans = [(idx, level) for idx in idxs]
    len_spans = len(all_spans)
    # we are going to do a minimum of 3 times in case there are de-clustered items
    # from previous iterations.
    step_size = int(step_size_percentage*kmeans_batch_size)
    num_times = max(max_num_retries_cluster,math.ceil(len_spans/step_size))
    if use_tqdm:
      num_times2 = tqdm.tqdm(range(num_times))
    else:
      num_times2 = range(num_times)
    for times in num_times2:
        max_rng = min(len_spans, step_size)
        #create the next batch to cluster
        spans = all_spans[:max_rng]
        not_already_clustered = [span for span in all_spans[:max_rng-step_size] if span not in span2cluster_label]
        if len(not_already_clustered) > int(.5*kmeans_batch_size):
          spans.extend(random.sample(not_already_clustered, int(.5*kmeans_batch_size)))
        else:
          spans.extend(not_already_clustered)
        if len(spans) == 0: break
        already_clustered = [span for span in all_spans[:max_rng-step_size] if span in span2cluster_label]
        if len(already_clustered)  > int(recluster_threshold*kmeans_batch_size):
          spans.extend(random.sample(already_clustered, int(.5*kmeans_batch_size)))
        else:
          spans.extend(already_clustered)
        embedding_idxs = [span[0] for span in spans]
        #do kmeans clustering in batches with the embedding indexes
        if level == 0:
          true_k = int(len(embedding_idxs)/prefered_leaf_node_size)
        else:
          true_k = int(len(embedding_idxs)/max_cluster_size)
        cluster_embeddings = np_memmap(mmap_file, shape=[mmap_len, embed_dim], idxs=embedding_idxs, dtype=dtype)
        new_labels = _cluster_one_batch(true_k,  spans, clusters, span2cluster_label, level, cluster_embeddings, min_overlap_merge_cluster, device)
        if not new_labels: break
        need_more = False
        if times <= num_times-2:
          for label in new_labels:
            if len(clusters[label]) < prefered_leaf_node_size:
              del clusters[label]
              need_more = True
        if not need_more: break
    # prepare data for next level clustering
    idxs  = [val[0][0] for key, val in clusters.items() if key[1] == level]
    if len(idxs ) < max_cluster_size: break
  return (clusters, span2cluster_label)

from transformers import AutoTokenizer, AutoModel
import torch
from datasets import load_dataset

import tqdm
device = 'cuda'

try:
  if tokenizer is None: assert False
except:
  # Load model from HuggingFace Hub
  tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-large-en-v1.5')
  model = AutoModel.from_pretrained('BAAI/bge-large-en-v1.5').half().eval().to(device)
import glob, json

from datasets import load_dataset

def embed_and_cluster(train = [], dtype=np.float32, curr = 0, mmap_file = "knowledge_with_instructions_clustered.mmap", clear_mmap=True,
                        embeds = None, mapper = None, embed_dim = 100, dest_folder="/content/drive/Shareddrives/ontocord_llc"):
  """
  load the data from the appropriate file. the records should have a 'text' and an 'instruct' field. the text field is used to cluster.
  the instruct field if non-empty will be stored in the resultant dataset. otherwise the text field will be used.
  """

  if clear_mmap:
    !rm $mmap_file

  print ('### Embed')
  random.shuffle(train)
  for rng in tqdm.tqdm(range(0, len(train), 2000)):
        sentences = [a[:200] if len(a) > 200 else a for a in [a['text'].replace("Fiction:", "").replace("Lesson:", "").replace("Title:","").replace("Lesson 1:", "").replace("Introduction to ", "").replace("Core Values:", "").replace("Understanding the ", "").replace("Understanding ", "").strip() for a in train[rng:min(len(train),rng+2000)]]]
        with torch.no_grad():
          sentence_embeddings = model(** tokenizer(sentences, padding=True, truncation=True, return_tensors='pt').to(device))[0][:, 0]
          if mapper is None:
            torch.manual_seed(123456)
            mapper = torch.nn.Linear(sentence_embeddings.shape[1], embed_dim).half().eval().to(device)
          sentence_embeddings = mapper(sentence_embeddings)
          sentence_embeddings = sentence_embeddings.cpu().numpy()
          embed_len = sentence_embeddings.shape[0]
          np_memmap(mmap_file, shape=[curr+embed_len, embed_dim], embeds=sentence_embeddings, idxs=range(curr, curr+embed_len), dtype=dtype)
          curr = curr+embed_len

  torch.cuda.empty_cache()
  print ('### Start clustering')
  clusters, span2label = create_hiearchical_clusters(mmap_file, 100, max_cluster_size=50, mmap_dtype=dtype, kmeans_batch_size=300000, use_tqdm=True)

  print ('### Saving clustered dataset')
  with open(mmap_file.replace(".mmap", "")+".jsonl", "w") as outf:
    for key, val in tqdm.tqdm(clusters.items()):
      outf.write(json.dumps({"text": "<|endoftext|>".join(train[v[0]]['text'].strip() if 'instruct' not in train[v[0]] else train[v[0]]['instruct'].strip() for v in val), "metadata": {'cluster_level': val[0][1], 'source': [train[v[0]]['metadata']['source'] if 'metadata' in train[v[0]] else train[v[0]]['meta']['source']  for v in val]}})+"\n")
  !cp knowledge_with_instructions_clustered.* $dest_folder
